### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vipinbeni** [mountainstorm/MobileDevice#19]
Hi Sir,
Now i  install it successfully but a new error is coming i attaching my error . how to import this dll
![errcore](https://cloud.githubusercontent.com/assets/5228833/2926229/ab27c2a4-d759-11e3-9b6b-9f5c5fb5adbd.JPG)

  ,i want to extract all photo and vedio from appliction like flickr ,instagram ,imovie etc can this possible with script . 

I m windows user

please help me 

thanks

**Comment by delvinj** [comment]
I'm not sure where Windows support stands, but I was able to get a little bit further than the above by commenting the following in MobileDevice.py.

`AMDeviceMountImage`
`AMDeviceUSBDeviceID`
`AMDeviceUSBProductID`

So I can at least enumerate, connect() and disconnect() to devices. So far so good.

However when I try using the device with WebKitInspector, I get the following:

        Traceback (most recent call last):
      File "test.py", line 70, in <module>
        devices_test()
      File "test.py", line 44, in devices_test
        inspector.navigate(u"<snip>");
      File "E:\Files\MobileDevice\webkitinspector.py", line 141, in navigate
        self.reportIdentifier(conn)
      File "E:\Files\MobileDevice\webkitinspector.py", line 53, in reportIdentifier
        u'WIRConnectionIdentifierKey': connection_uuid,
      File "E:\Files\MobileDevice\wirservice.py", line 48, in _sendmsg
        u'WIRFinalMessageKey': wi[start:end]
      File "E:\Files\MobileDevice\plistservice.py", line 59, in _sendmsg
        os.write(self.s, struct.pack(endian.encode(u'utf-8'), len(data)))
    OSError: [Errno 9] Bad file descriptor

**Comment by leandroprz** [comment]
I'm experiencing the same issue.
Any plans on updating the script to support Windows?
